title: Rivers blog
description: I am writing about my experiences in JS and digital creative.
author:
  name: River,
  email: riverfeya@gmail.com,
  url: https://github.com/riverfeya/base-blog/edit/master/_data/site.yml
